[VCS] - Started adding in restrictive functionality to stop third party modules from being edited
[VCS] (2) - Started adding in restrictive functionality to stop third party modules from being edited

[VCS] (3) - Started adding in restrictive functionality to stop third party modules from being edited

[VCS] (4) - Started adding in restrictive functionality to stop third party modules from being edited

[VCS] (5) - Started adding in restrictive functionality to stop third party modules from being edited

[VCS] 65) - Started adding in restrictive functionality to stop third party modules from being edited

[VCS] (7) - Started adding in restrictive functionality to stop third party modules from being edited

[VCS] (8) - Started adding in restrictive functionality to stop third party modules from being edited

[VCS] (9) - Started adding in restrictive functionality to stop third party modules from being edited

diff --git a/Api/ThirdParty/Vcs/hooks/bash/commit-msg b/Api/ThirdParty/Vcs/hooks/bash/commit-msg
--- a/Api/ThirdParty/Vcs/hooks/bash/commit-msg
+++ b/Api/ThirdParty/Vcs/hooks/bash/commit-msg
@@ -32,4 +32,12 @@ else
   echo "No commit-msg scripts found in $HOOK_DIR."
 fi
 
+
+cd ../../
+
+dotnet run git commit-msg "$COMMIT_MSG_FILE" || {
+  echo "Dotnet script failed. Aborting commit."
+  exit 1
+}
+
 exit 0
diff --git a/Api/ThirdParty/Vcs/hooks/bash/pre-commit b/Api/ThirdParty/Vcs/hooks/bash/pre-commit
--- a/Api/ThirdParty/Vcs/hooks/bash/pre-commit
+++ b/Api/ThirdParty/Vcs/hooks/bash/pre-commit
@@ -29,4 +29,12 @@ else
   echo "No pre-commit scripts found in $HOOK_DIR."
 fi
 
+
+cd ../../
+
+dotnet run git pre-commit || {
+  echo "Dotnet script failed. Aborting commit."
+  exit 1
+}
+
 exit 0
diff --git a/Api/ThirdParty/Vcs/hooks/bash/pre-push b/Api/ThirdParty/Vcs/hooks/bash/pre-push
--- a/Api/ThirdParty/Vcs/hooks/bash/pre-push
+++ b/Api/ThirdParty/Vcs/hooks/bash/pre-push
@@ -33,4 +33,11 @@ else
   echo "No pre-push scripts found in $HOOK_DIR."
 fi
 
+cd ../../
+
+dotnet run git pre-push "$COMMIT_MSG_FILE" || {
+  echo "Dotnet script failed. Aborting commit."
+  exit 1
+}
+
 exit 0
